### ISSUE TITLE
Please add support for CLEU payload

### ISSUE THREAD

**Issue by MattZeeX** [brittyazel/ViragDevTool#3]
Sorry I don't really know coding/github so not going to make a pull/push request or whatever it's called.

In BFA they removed the payload from CLEU, and you need to instead use CombatLogGetCurrentEventInfo to access the payload. Previously with VDT you could just click on the CLEU event and see the args, but now it does not work.

A very helpful users in the WeakAuras discord suggested I add this:
```
if event == "COMBAT_LOG_EVENT_UNFILTERED" then
    args = { event, CombatLogGetCurrentEventInfo() }
end
```
snippet to [line 81](https://github.com/varren/ViragDevTool/blob/ddc34bd8c7eb194bd4b2dc8c4e31d24dcef18406/Modules/ViragDevToolEvents.lua#L81) of the old github. I instead decided to do so at [line 85](https://github.com/brittyazel/ViragDevTool/blob/master/Modules/ViragDevToolEvents.lua#L85) of your github and it appears to function well in my game in my limited (2 mins) testing.

When you are free could you please add this to the addon, thank you and I really appreciate you picking up the addon in the original author's absence!

**Comment by brittyazel** [comment]
Thanks! Just added and can confirm that it works
